In [5]:
import pandas as pd
import json
import pickle

In [2]:
with open("rules.json", "r", encoding="utf-8") as f:
    rules_data = json.load(f)

df = pd.DataFrame(rules_data)
df.head(5)

,core-id,cdisc_rule_id,standard,executability,status,standard_source,core_id_is_null,core_id_startswith_CORE,in_cache,rule_in_mltple_standards,sharepoint_source,negative_folder_path,negative_regressions,positive_folder_path,positive_regressions
0,CDISC.ADAMIG.111,111,ADaMIG,Fully Executable,Draft,ADAMIG,False,False,False,[],NaN,NaN,NaN,NaN,NaN
1,CDISC.ADAMIG.252,252,ADaMIG,Fully Executable,Draft,ADAMIG,False,False,False,[],NaN,NaN,NaN,NaN,NaN
2,CDISC.ADAMIG.AD0019,19,ADaMIG,Fully Executable,Draft,ADAMIG,False,False,False,[],NaN,NaN,NaN,NaN,NaN
3,CDISC.ADAMIG.AD0020,20,ADaMIG,Fully Executable,Draft,ADAMIG,False,False,False,[],NaN,NaN,NaN,NaN,NaN
4,CDISC.ADAMIG.AD0021,21,ADaMIG,Fully Executable,Draft,ADAMIG,False,False,False,[],NaN,NaN,NaN,NaN,NaN

In [13]:

with open("../../../resources/cache/rules.pkl", "rb") as f:
    rules = pickle.load(f)
rules = pd.DataFrame(rules).transpose()
rules.head(5)

,core_id,author,reference,sensitivity,executability,description,authorities,standards,classes,domains,entities,rule_type,conditions,actions,use_case,output_variables,datasets,operations
CORE-000351,CORE-000351,CDISC,[[{'Citations': [{'Cited_Guidance': 'Identifie...,Record,partially executable,USUBJID must be unique across all studies,"[{'Organization': 'CDISC', 'Standards': [{'Nam...","[{'Name': 'SDTMIG', 'Version': '3.4', 'Substan...",{'Include': ['SPECIAL PURPOSE']},{'Include': ['DM']},None,Record Data,"{'all': [{'name': 'get_dataset', 'operator': '...","[{'name': 'generate_dataset_error_objects', 'p...","NONCLIN, INDH",[USUBJID],NaN,NaN
CORE-000793,CORE-000793,CDISC,[[{'Citations': [{'Cited_Guidance': 'Collectio...,Dataset,fully executable,When date/time of collection (--DTC) is popula...,"[{'Organization': 'FDA', 'Standards': [{'Name'...","[{'Name': 'SDTMIG', 'Version': '3.2', 'Substan...",{'Include': ['ALL']},{'Include': ['ALL']},None,Record Data,"{'all': [{'name': 'get_dataset', 'operator': '...","[{'name': 'generate_dataset_error_objects', 'p...",None,NaN,NaN,NaN
CORE-000252,CORE-000252,CDISC,[[{'Citations': [{'Cited_Guidance': 'Indicates...,Record,fully executable,"When DS.DSDECOD is 'DEATH', DTHFL must be 'Y'","[{'Organization': 'CDISC', 'Standards': [{'Nam...","[{'Name': 'SDTMIG', 'Version': '3.4', 'Substan...",{'Include': ['SPECIAL PURPOSE']},{'Include': ['DM']},None,Record Data,"{'all': [{'name': 'get_dataset', 'operator': '...","[{'name': 'generate_dataset_error_objects', 'p...",INDH,NaN,"[{'domain_name': 'DS', 'match_key': ['USUBJID'...",NaN
CORE-000740,CORE-000740,CDISC,[[{'Citations': [{'Cited_Guidance': 'Further i...,Record,fully executable,A required value of TSPARMCD is not found,"[{'Organization': 'CDISC', 'Standards': [{'Nam...","[{'Name': 'SDTMIG', 'Version': '3.2', 'Substan...",{'Include': ['TRIAL DESIGN']},{'Include': ['TS']},None,Record Data,"{'all': [{'name': 'get_dataset', 'operator': '...","[{'name': 'generate_dataset_error_objects', 'p...",None,[TSPARMCD],NaN,NaN
CORE-000791,CORE-000791,CDISC,[[{'Citations': [{'Cited_Guidance': 'All paire...,Record,fully executable,ACTARMCD and ACTARM should have a one-to-one r...,"[{'Organization': 'FDA', 'Standards': [{'Name'...","[{'Name': 'SDTMIG', 'Version': '3.2', 'Substan...",{'Include': ['SPECIAL PURPOSE']},{'Include': ['DM']},None,Record Data,"{'all': [{'name': 'get_dataset', 'operator': '...","[{'name': 'generate_dataset_error_objects', 'p...",None,"[ACTARM, ACTARMCD]",NaN,NaN

In [28]:

test_data = df.explode("positive_regressions")
test_data = test_data[test_data["positive_regressions"].notnull()]
test_data['positive_regressions'] = test_data['positive_regressions'].apply(lambda v: next(val['engine_regression'] for val in v.values()))
test_data = test_data[test_data['positive_regressions'].notnull()]
test_data.head(5)

,core-id,cdisc_rule_id,standard,executability,status,standard_source,core_id_is_null,core_id_startswith_CORE,in_cache,rule_in_mltple_standards,sharepoint_source,negative_folder_path,negative_regressions,positive_folder_path,positive_regressions
233,CORE-000001,"CG0176, TIG0405","SDTMIG, TIG",Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0176/negative,[{'SDTMIG/CG0176/negative/01': {'test_case_xsl...,SDTMIG/CG0176/positive,"{'define_xml_present': False, 'datasets_conver..."
234,CORE-000002,CG0208,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0208/negative,[{'SDTMIG/CG0208/negative/01': {'test_case_xsl...,SDTMIG/CG0208/positive,"{'define_xml_present': False, 'datasets_conver..."
236,CORE-000004,"CG0101, TIG0366","SDTMIG, TIG",Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0101/negative,[{'SDTMIG/CG0101/negative/01': {'test_case_xsl...,SDTMIG/CG0101/positive,"{'define_xml_present': False, 'datasets_conver..."
237,CORE-000005,CG0102,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0102/negative,[{'SDTMIG/CG0102/negative/01': {'test_case_xsl...,SDTMIG/CG0102/positive,"{'define_xml_present': False, 'datasets_conver..."
238,CORE-000006,"CG0131, TIG0381","SDTMIG, TIG",Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0131/negative,[{'SDTMIG/CG0131/negative/01': {'test_case_xsl...,SDTMIG/CG0131/positive,"{'define_xml_present': False, 'datasets_conver..."

In [32]:
test_data['comparison'] = test_data["positive_regressions"].map(lambda v: v.get('old_vs_sql', None))
test_data = test_data[test_data['comparison'].notnull()]
test_data = test_data[[c.get("equal", None) is None for c in test_data['comparison']]]
test_data = test_data[[c.get("number_of_errors_mismatch", False) for c in test_data['comparison']]]
test_data[10:15]

,core-id,cdisc_rule_id,standard,executability,status,standard_source,core_id_is_null,core_id_startswith_CORE,in_cache,rule_in_mltple_standards,sharepoint_source,negative_folder_path,negative_regressions,positive_folder_path,positive_regressions,comparison
573,CORE-000468,CG0276,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0276/negative,[{'SDTMIG/CG0276/negative/01': {'test_case_xsl...,SDTMIG/CG0276/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
574,CORE-000469,CG0277,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0277/negative,[{'SDTMIG/CG0277/negative/01': {'test_case_xsl...,SDTMIG/CG0277/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
575,CORE-000470,CG0278,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0278/negative,[{'SDTMIG/CG0278/negative/01': {'test_case_xsl...,SDTMIG/CG0278/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
576,CORE-000473,CG0272,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0272/negative,[{'SDTMIG/CG0272/negative/01': {'test_case_xsl...,SDTMIG/CG0272/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."
576,CORE-000473,CG0272,SDTMIG,Fully Executable,Published,SDTMIG,False,True,True,[],SDTMIG,SDTMIG/CG0272/negative,[{'SDTMIG/CG0272/negative/01': {'test_case_xsl...,SDTMIG/CG0272/positive,"{'define_xml_present': False, 'datasets_conver...","{'dataset_mismatch': False, 'execution_status_..."

In [27]:
simple_rule_types = [
    'Record Data',
    'Dataset Contents Check against Define XML and Library Metadata',
    'Value Level Metadata Check against Define XML'
]
not_simple_rules = rules[[r not in simple_rule_types for r in rules['rule_type']]]
print(len(not_simple_rules), "not simple rules")
print(not_simple_rules['rule_type'].unique())
not_simple_rules['core_id'].sort_values().head(5)

37 not simple rules
['Dataset Metadata Check' 'Domain Presence Check'
 'Variable Metadata Check'
 'Variable Metadata Check against Library Metadata'
 'Value Check with Dataset Metadata'
 'Variable Metadata Check against Define XML'
 'Define Item Metadata Check against Library Metadata']

CORE-000019    CORE-000019
CORE-000042    CORE-000042
CORE-000043    CORE-000043
CORE-000044    CORE-000044
CORE-000182    CORE-000182
Name: core_id, dtype: object